// Intensity is continuous from 1 (easy/innocent) to 100 (bold/adult).
// Keep prompts consensual, legal, and possible in an ordinary living-room setting.
window.PROMPTS = [
  {id:"t001",type:"truth",category:"icebreaker",intensity:5,minPlayers:2,text:"What is the most useless talent you have?"},
  {id:"t002",type:"truth",category:"icebreaker",intensity:7,minPlayers:2,text:"What song do you know every word to?"},
  {id:"t003",type:"truth",category:"personal",intensity:9,minPlayers:2,text:"What tiny thing instantly improves your mood?"},
  {id:"t004",type:"truth",category:"social",intensity:11,minPlayers:3,text:"Who here would survive longest on a deserted island?"},
  {id:"t005",type:"truth",category:"funny",intensity:12,minPlayers:2,text:"What is your strangest food combination?"},
  {id:"t006",type:"truth",category:"personal",intensity:14,minPlayers:2,text:"What was your most embarrassing fashion phase?"},
  {id:"t007",type:"truth",category:"social",intensity:16,minPlayers:3,text:"Who here gives the best first impression?"},
  {id:"t008",type:"truth",category:"personal",intensity:18,minPlayers:2,text:"What is a harmless lie you tell surprisingly often?"},
  {id:"t009",type:"truth",category:"funny",intensity:20,minPlayers:2,text:"What is the weirdest thing in your camera roll?"},
  {id:"t010",type:"truth",category:"social",intensity:22,minPlayers:3,text:"Who here would you trust to plan a surprise party for you?"},
  {id:"t011",type:"truth",category:"personal",intensity:24,minPlayers:2,text:"What opinion have you completely changed your mind about?"},
  {id:"t012",type:"truth",category:"confession",intensity:26,minPlayers:2,text:"When did you last pretend to understand something you did not?"},
  {id:"t013",type:"truth",category:"social",intensity:28,minPlayers:4,text:"Who here would be the best—and worst—travel companion?"},
  {id:"t014",type:"truth",category:"personal",intensity:30,minPlayers:2,text:"What compliment do you still remember?"},
  {id:"t015",type:"truth",category:"confession",intensity:32,minPlayers:2,text:"What is the pettiest reason you have disliked someone?"},
  {id:"t016",type:"truth",category:"relationships",intensity:34,minPlayers:2,text:"What is your biggest friendship green flag?"},
  {id:"t017",type:"truth",category:"social",intensity:36,minPlayers:3,text:"Who here would you call first if you got into trouble?"},
  {id:"t018",type:"truth",category:"confession",intensity:38,minPlayers:2,text:"What is something you judged before secretly trying it?"},
  {id:"t019",type:"truth",category:"relationships",intensity:40,minPlayers:2,text:"What is the quickest way for someone to lose your interest?"},
  {id:"t020",type:"truth",category:"personal",intensity:42,minPlayers:2,text:"What insecurity have you mostly overcome?"},
  {id:"t021",type:"truth",category:"social",intensity:44,minPlayers:4,text:"Who here do you think is the hardest to read?"},
  {id:"t022",type:"truth",category:"confession",intensity:46,minPlayers:2,text:"What is the longest you have stalked someone’s social profile?"},
  {id:"t023",type:"truth",category:"relationships",intensity:48,minPlayers:2,text:"What is your most irrational dating deal-breaker?"},
  {id:"t024",type:"truth",category:"confession",intensity:50,minPlayers:2,text:"What message have you typed and wisely never sent?"},
  {id:"t025",type:"truth",category:"social",intensity:52,minPlayers:3,text:"Who here would you most want as your wingperson?"},
  {id:"t026",type:"truth",category:"relationships",intensity:54,minPlayers:2,text:"Have you ever developed feelings for someone you should not have?"},
  {id:"t027",type:"truth",category:"personal",intensity:56,minPlayers:2,text:"What part of your personality do people misunderstand?"},
  {id:"t028",type:"truth",category:"confession",intensity:58,minPlayers:2,text:"What is the most awkward excuse you used to leave a date or party?"},
  {id:"t029",type:"truth",category:"relationships",intensity:60,minPlayers:2,text:"What is the boldest move you have made on a crush?"},
  {id:"t030",type:"truth",category:"social",intensity:62,minPlayers:4,text:"Who here could talk their way out of almost anything?"},
  {id:"t031",type:"truth",category:"confession",intensity:64,minPlayers:2,text:"Have you ever kept talking to someone just for the attention?"},
  {id:"t032",type:"truth",category:"relationships",intensity:66,minPlayers:2,text:"What is something you wish an ex or old crush had understood?"},
  {id:"t033",type:"truth",category:"social",intensity:68,minPlayers:3,text:"What was your honest first impression of the person opposite you?"},
  {id:"t034",type:"truth",category:"confession",intensity:70,minPlayers:2,text:"What secret have you almost revealed by accident?"},
  {id:"t035",type:"truth",category:"relationships",intensity:72,minPlayers:2,text:"What makes someone instantly attractive to you?"},
  {id:"t036",type:"truth",category:"personal",intensity:74,minPlayers:2,text:"What boundary did you learn only after someone crossed it?"},
  {id:"t037",type:"truth",category:"confession",intensity:76,minPlayers:2,text:"What is the most jealous you have ever been?"},
  {id:"t038",type:"truth",category:"relationships",intensity:78,minPlayers:2,text:"Have you ever kissed someone and immediately regretted it?"},
  {id:"t039",type:"truth",category:"social",intensity:80,minPlayers:4,text:"Who here do you think has the wildest dating history?"},
  {id:"t040",type:"truth",category:"confession",intensity:82,minPlayers:2,text:"What is something romantic you pretend not to care about?"},
  {id:"t041",type:"truth",category:"relationships",intensity:84,minPlayers:2,text:"What is the closest you have come to being caught in an intimate moment?"},
  {id:"t042",type:"truth",category:"confession",intensity:86,minPlayers:2,text:"Have you ever lied about your feelings to protect your pride?"},
  {id:"t043",type:"truth",category:"relationships",intensity:88,minPlayers:2,text:"What is your biggest turn-on that has nothing to do with looks?"},
  {id:"t044",type:"truth",category:"social",intensity:90,minPlayers:3,text:"Who in this room would you be most nervous to go on a date with?"},
  {id:"t045",type:"truth",category:"confession",intensity:92,minPlayers:2,text:"What is the riskiest romantic decision you have made?"},
  {id:"t046",type:"truth",category:"relationships",intensity:94,minPlayers:2,text:"What is one intimate question you wish people asked more honestly?"},
  {id:"t047",type:"truth",category:"confession",intensity:96,minPlayers:2,text:"What attraction have you never admitted out loud?"},
  {id:"t048",type:"truth",category:"relationships",intensity:98,minPlayers:2,text:"What is the boldest fantasy date you would genuinely say yes to?"},

  {id:"d001",type:"dare",category:"icebreaker",intensity:5,minPlayers:2,text:"Do your best victory dance for ten seconds."},
  {id:"d002",type:"dare",category:"performance",intensity:7,minPlayers:2,text:"Speak in a dramatic movie-trailer voice until your next turn."},
  {id:"d003",type:"dare",category:"funny",intensity:9,minPlayers:2,text:"Balance a small object on your head for one round."},
  {id:"d004",type:"dare",category:"performance",intensity:11,minPlayers:2,text:"Hum a song until someone guesses it."},
  {id:"d005",type:"dare",category:"social",intensity:13,minPlayers:3,text:"Give everyone in the circle a one-word award."},
  {id:"d006",type:"dare",category:"funny",intensity:15,minPlayers:2,text:"Let the group choose a new pose for your next photo."},
  {id:"d007",type:"dare",category:"performance",intensity:17,minPlayers:2,text:"Act like a cat until someone says your name."},
  {id:"d008",type:"dare",category:"social",intensity:19,minPlayers:3,text:"Give the person to your left a sincere compliment."},
  {id:"d009",type:"dare",category:"funny",intensity:21,minPlayers:2,text:"Try to make the group laugh without speaking."},
  {id:"d010",type:"dare",category:"performance",intensity:23,minPlayers:2,text:"Give a thirty-second speech about why socks are important."},
  {id:"d011",type:"dare",category:"social",intensity:25,minPlayers:3,text:"Imitate someone in the room until the group guesses who."},
  {id:"d012",type:"dare",category:"funny",intensity:27,minPlayers:2,text:"Show the last meme you saved, if you are comfortable."},
  {id:"d013",type:"dare",category:"performance",intensity:29,minPlayers:2,text:"Perform the chorus of a song chosen by the group."},
  {id:"d014",type:"dare",category:"social",intensity:31,minPlayers:3,text:"Trade seats with the person you know least."},
  {id:"d015",type:"dare",category:"funny",intensity:33,minPlayers:2,text:"Let another player give you a harmless nickname for three rounds."},
  {id:"d016",type:"dare",category:"performance",intensity:35,minPlayers:2,text:"Re-enact your morning routine in twenty seconds."},
  {id:"d017",type:"dare",category:"social",intensity:37,minPlayers:3,text:"Tell the group two truths and a lie; let them guess the lie."},
  {id:"d018",type:"dare",category:"funny",intensity:39,minPlayers:2,text:"Read your most recent emoji sequence like a serious poem."},
  {id:"d019",type:"dare",category:"social",intensity:41,minPlayers:3,text:"Let the group choose a word you must use before your next turn."},
  {id:"d020",type:"dare",category:"performance",intensity:43,minPlayers:2,text:"Do your best impression of someone flirting badly."},
  {id:"d021",type:"dare",category:"social",intensity:45,minPlayers:3,text:"Hold eye contact with the person opposite you for fifteen seconds."},
  {id:"d022",type:"dare",category:"confession",intensity:47,minPlayers:2,text:"Show your phone wallpaper and explain the story behind it."},
  {id:"d023",type:"dare",category:"performance",intensity:49,minPlayers:2,text:"Deliver your best cheesy pickup line to an imaginary stranger."},
  {id:"d024",type:"dare",category:"social",intensity:51,minPlayers:3,text:"Let the group ask one follow-up question to your last answer."},
  {id:"d025",type:"dare",category:"flirty",intensity:53,minPlayers:3,text:"Give a genuine compliment to the person the group chooses."},
  {id:"d026",type:"dare",category:"performance",intensity:55,minPlayers:2,text:"Demonstrate your signature dance move with full confidence."},
  {id:"d027",type:"dare",category:"social",intensity:57,minPlayers:3,text:"Rank three qualities you value most in a partner."},
  {id:"d028",type:"dare",category:"flirty",intensity:59,minPlayers:3,text:"Describe your ideal first date in exactly ten words."},
  {id:"d029",type:"dare",category:"social",intensity:61,minPlayers:4,text:"Let everyone vote on which celebrity could play you in a movie."},
  {id:"d030",type:"dare",category:"flirty",intensity:63,minPlayers:3,text:"Give your smoothest pickup line to the person opposite you."},
  {id:"d031",type:"dare",category:"confession",intensity:65,minPlayers:2,text:"Read the last harmless text you sent in your most dramatic voice."},
  {id:"d032",type:"dare",category:"flirty",intensity:67,minPlayers:3,text:"Let someone choose a romantic song for your ten-second slow dance."},
  {id:"d033",type:"dare",category:"social",intensity:69,minPlayers:3,text:"Say one thing you admire about the person to your right."},
  {id:"d034",type:"dare",category:"flirty",intensity:71,minPlayers:3,text:"Recreate your best dating-profile pose."},
  {id:"d035",type:"dare",category:"performance",intensity:73,minPlayers:2,text:"Act out how you behave when you have a crush."},
  {id:"d036",type:"dare",category:"flirty",intensity:75,minPlayers:3,text:"Whisper a playful compliment to a consenting player of your choice."},
  {id:"d037",type:"dare",category:"social",intensity:77,minPlayers:4,text:"Let the group invent a fictional dating-app bio for you."},
  {id:"d038",type:"dare",category:"flirty",intensity:79,minPlayers:3,text:"Give a five-second runway walk aimed at a consenting player."},
  {id:"d039",type:"dare",category:"confession",intensity:81,minPlayers:2,text:"Reveal the last person you searched for online—or use your skip."},
  {id:"d040",type:"dare",category:"flirty",intensity:83,minPlayers:3,text:"Let a consenting player choose a new lock-screen selfie pose for you."},
  {id:"d041",type:"dare",category:"social",intensity:85,minPlayers:3,text:"Describe the person opposite you as if they were the lead in a romance novel."},
  {id:"d042",type:"dare",category:"flirty",intensity:87,minPlayers:3,text:"Give a consenting player a twenty-second hand massage."},
  {id:"d043",type:"dare",category:"performance",intensity:89,minPlayers:2,text:"Perform a dramatic proposal to an inanimate object."},
  {id:"d044",type:"dare",category:"flirty",intensity:91,minPlayers:3,text:"Let the group choose someone for you to serenade for fifteen seconds."},
  {id:"d045",type:"dare",category:"social",intensity:93,minPlayers:4,text:"Tell the group who you would choose as a fake date to a wedding and why."},
  {id:"d046",type:"dare",category:"flirty",intensity:95,minPlayers:3,text:"Give a consenting player your best intense movie-scene eye contact."},
  {id:"d047",type:"dare",category:"confession",intensity:97,minPlayers:2,text:"Show the group your most-used dating or flirting emoji—or use your skip."},
  {id:"d048",type:"dare",category:"flirty",intensity:99,minPlayers:3,text:"Describe your dream romantic evening like a luxury advertisement."},

  {id:"t049",type:"truth",category:"icebreaker",intensity:4,minPlayers:2,text:"What fictional world would you happily live in for a week?"},
  {id:"t050",type:"truth",category:"funny",intensity:8,minPlayers:2,text:"What is the silliest thing you believed as a child?"},
  {id:"t051",type:"truth",category:"personal",intensity:12,minPlayers:2,text:"Which ordinary skill are you strangely proud of?"},
  {id:"t052",type:"truth",category:"group",intensity:15,minPlayers:3,text:"Who here would make the best game-show host?"},
  {id:"t053",type:"truth",category:"icebreaker",intensity:18,minPlayers:2,text:"What would the title of your autobiography be?"},
  {id:"t054",type:"truth",category:"funny",intensity:21,minPlayers:2,text:"What is your most irrational everyday fear?"},
  {id:"t055",type:"truth",category:"group",intensity:24,minPlayers:4,text:"Who here is most likely to accidentally become famous?"},
  {id:"t056",type:"truth",category:"personal",intensity:27,minPlayers:2,text:"What habit are you currently trying to build or break?"},
  {id:"t057",type:"truth",category:"confession",intensity:30,minPlayers:2,text:"What purchase did you regret almost immediately?"},
  {id:"t058",type:"truth",category:"group",intensity:33,minPlayers:3,text:"Who here would you want on your team for a pub quiz?"},
  {id:"t059",type:"truth",category:"personal",intensity:36,minPlayers:2,text:"What is something you are more competitive about than you admit?"},
  {id:"t060",type:"truth",category:"confession",intensity:39,minPlayers:2,text:"What is the worst advice you have ever followed?"},
  {id:"t061",type:"truth",category:"relationships",intensity:42,minPlayers:2,text:"What quality makes you feel safe around someone?"},
  {id:"t062",type:"truth",category:"group",intensity:45,minPlayers:4,text:"Who here is most likely to remember everyone’s birthday?"},
  {id:"t063",type:"truth",category:"confession",intensity:48,minPlayers:2,text:"When have you blamed bad luck for something that was your fault?"},
  {id:"t064",type:"truth",category:"personal",intensity:51,minPlayers:2,text:"What is something you wish you were brave enough to try?"},
  {id:"t065",type:"truth",category:"relationships",intensity:54,minPlayers:2,text:"What is your most underrated relationship green flag?"},
  {id:"t066",type:"truth",category:"group",intensity:57,minPlayers:3,text:"Whose life here would make the most entertaining reality show?"},
  {id:"t067",type:"truth",category:"confession",intensity:60,minPlayers:2,text:"Have you ever rehearsed a conversation before having it?"},
  {id:"t068",type:"truth",category:"relationships",intensity:63,minPlayers:2,text:"What is the most romantic thing someone could do without spending money?"},
  {id:"t069",type:"truth",category:"personal",intensity:66,minPlayers:2,text:"What truth about yourself took you a long time to accept?"},
  {id:"t070",type:"truth",category:"group",intensity:69,minPlayers:4,text:"Who here seems most likely to have a secret adventurous side?"},
  {id:"t071",type:"truth",category:"confession",intensity:72,minPlayers:2,text:"What is the most obvious hint you completely missed?"},
  {id:"t072",type:"truth",category:"relationships",intensity:75,minPlayers:2,text:"What is a dating rule you think is completely outdated?"},
  {id:"t073",type:"truth",category:"confession",intensity:78,minPlayers:2,text:"Have you ever acted uninterested because you liked someone too much?"},
  {id:"t074",type:"truth",category:"group",intensity:81,minPlayers:3,text:"Who here would you trust to write your dating profile?"},
  {id:"t075",type:"truth",category:"relationships",intensity:84,minPlayers:2,text:"What kind of chemistry is hardest for you to resist?"},
  {id:"t076",type:"truth",category:"confession",intensity:87,minPlayers:2,text:"What is the boldest text you have ever sent after midnight?"},
  {id:"t077",type:"truth",category:"personal",intensity:90,minPlayers:2,text:"What desire do you tend to downplay when talking to other people?"},
  {id:"t078",type:"truth",category:"relationships",intensity:93,minPlayers:2,text:"What is something you need before you can fully trust a romantic partner?"},
  {id:"t079",type:"truth",category:"group",intensity:96,minPlayers:4,text:"Who here do you think could charm their way into an exclusive party?"},
  {id:"t080",type:"truth",category:"confession",intensity:99,minPlayers:2,text:"What is the most tempting bad idea you have seriously considered?"},
  {id:"t081",type:"truth",category:"icebreaker",intensity:10,minPlayers:2,text:"Which three items would you take to a deserted island?"},
  {id:"t082",type:"truth",category:"funny",intensity:25,minPlayers:2,text:"What is the funniest misunderstanding you have been part of?"},
  {id:"t083",type:"truth",category:"group",intensity:40,minPlayers:3,text:"Who here would be best at keeping a surprise secret?"},
  {id:"t084",type:"truth",category:"personal",intensity:55,minPlayers:2,text:"What is a goal you rarely tell people about?"},
  {id:"t085",type:"truth",category:"confession",intensity:70,minPlayers:2,text:"What is the most embarrassing way you tried to impress someone?"},
  {id:"t086",type:"truth",category:"relationships",intensity:80,minPlayers:2,text:"What is a compliment from a crush that would completely disarm you?"},
  {id:"t087",type:"truth",category:"group",intensity:88,minPlayers:3,text:"Who here has the energy you would be most likely to flirt with at a party?"},
  {id:"t088",type:"truth",category:"relationships",intensity:97,minPlayers:2,text:"What is one romantic risk you would like to take someday?"},

  {id:"d049",type:"dare",category:"icebreaker",intensity:4,minPlayers:2,text:"Make your best animal sound and let the group guess it."},
  {id:"d050",type:"dare",category:"funny",intensity:8,minPlayers:2,text:"Walk across the room like the floor is made of jelly."},
  {id:"d051",type:"dare",category:"performance",intensity:12,minPlayers:2,text:"Pretend to accept an award for being excellent at doing nothing."},
  {id:"d052",type:"dare",category:"group",intensity:15,minPlayers:3,text:"Start a group wave and keep trying until everyone joins in."},
  {id:"d053",type:"dare",category:"funny",intensity:18,minPlayers:2,text:"Wear one harmless item backward until your next turn."},
  {id:"d054",type:"dare",category:"performance",intensity:21,minPlayers:2,text:"Narrate another player taking a sip like a wildlife documentary."},
  {id:"d055",type:"dare",category:"group",intensity:24,minPlayers:3,text:"Create a secret handshake with the person to your right."},
  {id:"d056",type:"dare",category:"funny",intensity:27,minPlayers:2,text:"Make up a slogan for yourself and announce it proudly."},
  {id:"d057",type:"dare",category:"performance",intensity:30,minPlayers:2,text:"Sell an ordinary object in the room as if it costs a million dollars."},
  {id:"d058",type:"dare",category:"group",intensity:33,minPlayers:4,text:"Assign every player a role in an imaginary heist."},
  {id:"d059",type:"dare",category:"social",intensity:36,minPlayers:3,text:"Ask the group to choose a celebrity impression for you to attempt."},
  {id:"d060",type:"dare",category:"performance",intensity:39,minPlayers:2,text:"Give a weather forecast for the mood in the room."},
  {id:"d061",type:"dare",category:"group",intensity:42,minPlayers:3,text:"Let the group choose one word you must avoid until your next turn."},
  {id:"d062",type:"dare",category:"social",intensity:45,minPlayers:3,text:"Give each player a sincere compliment using no repeated adjectives."},
  {id:"d063",type:"dare",category:"performance",intensity:48,minPlayers:2,text:"Act out your most awkward first-date greeting."},
  {id:"d064",type:"dare",category:"confession",intensity:51,minPlayers:2,text:"Show the group the oldest harmless photo still on your phone."},
  {id:"d065",type:"dare",category:"group",intensity:54,minPlayers:4,text:"Let the group invent a cocktail or mocktail named after you."},
  {id:"d066",type:"dare",category:"flirty",intensity:57,minPlayers:3,text:"Demonstrate how you would confidently introduce yourself to a crush."},
  {id:"d067",type:"dare",category:"social",intensity:60,minPlayers:3,text:"Let another player ask you one question you must answer in five words."},
  {id:"d068",type:"dare",category:"performance",intensity:63,minPlayers:2,text:"Act out receiving a text from someone you really like."},
  {id:"d069",type:"dare",category:"flirty",intensity:66,minPlayers:3,text:"Create a pickup line using an object chosen by the group."},
  {id:"d070",type:"dare",category:"group",intensity:69,minPlayers:4,text:"Let the group choose two players for you to cast in a romantic comedy."},
  {id:"d071",type:"dare",category:"confession",intensity:72,minPlayers:2,text:"Describe your last crush using only three vague clues."},
  {id:"d072",type:"dare",category:"flirty",intensity:75,minPlayers:3,text:"Give a consenting player a compliment without mentioning their appearance."},
  {id:"d073",type:"dare",category:"performance",intensity:78,minPlayers:2,text:"Act out your reaction to being asked on your dream date."},
  {id:"d074",type:"dare",category:"group",intensity:81,minPlayers:4,text:"Let the group vote on your most charming quality, then defend the result."},
  {id:"d075",type:"dare",category:"flirty",intensity:84,minPlayers:3,text:"Read a restaurant menu item as if it were a passionate love letter."},
  {id:"d076",type:"dare",category:"confession",intensity:87,minPlayers:2,text:"Share the first name of your earliest crush—or use your skip."},
  {id:"d077",type:"dare",category:"flirty",intensity:90,minPlayers:3,text:"Let a consenting player direct your best smoldering photo pose."},
  {id:"d078",type:"dare",category:"group",intensity:93,minPlayers:4,text:"Let the group design your ideal fictional partner in five traits."},
  {id:"d079",type:"dare",category:"flirty",intensity:96,minPlayers:3,text:"Deliver a ten-second romantic monologue to a consenting player or an object."},
  {id:"d080",type:"dare",category:"confession",intensity:99,minPlayers:2,text:"Describe your boldest dating move as if it were a breaking-news report."},
  {id:"d081",type:"dare",category:"icebreaker",intensity:10,minPlayers:2,text:"Invent a dance move and give it a ridiculous name."},
  {id:"d082",type:"dare",category:"funny",intensity:25,minPlayers:2,text:"Try to say the alphabet backward for fifteen seconds."},
  {id:"d083",type:"dare",category:"group",intensity:40,minPlayers:3,text:"Choose a player and make up a friendly superhero name for them."},
  {id:"d084",type:"dare",category:"social",intensity:55,minPlayers:3,text:"Describe everyone’s current mood using movie genres."},
  {id:"d085",type:"dare",category:"performance",intensity:70,minPlayers:2,text:"Show how you would walk into a room when you know your crush is there."},
  {id:"d086",type:"dare",category:"flirty",intensity:80,minPlayers:3,text:"Give a consenting player an over-the-top royal introduction."},
  {id:"d087",type:"dare",category:"group",intensity:88,minPlayers:4,text:"Let the group choose your fictional celebrity power-couple partner."},
  {id:"d088",type:"dare",category:"flirty",intensity:97,minPlayers:3,text:"Describe your ideal kiss using only movie titles or song titles."},

  {id:"t089",type:"truth",category:"icebreaker",intensity:4,minPlayers:2,text:"What smell always brings back a good memory?"},
  {id:"t090",type:"truth",category:"funny",intensity:6,minPlayers:2,text:"What is the worst haircut you have ever had?"},
  {id:"t091",type:"truth",category:"personal",intensity:8,minPlayers:2,text:"Which app do you use more than you should?"},
  {id:"t092",type:"truth",category:"group",intensity:10,minPlayers:3,text:"Who here would be the best teacher?"},
  {id:"t093",type:"truth",category:"icebreaker",intensity:12,minPlayers:2,text:"What is your favorite way to waste an afternoon?"},
  {id:"t094",type:"truth",category:"funny",intensity:14,minPlayers:2,text:"What is your funniest autocorrect mistake?"},
  {id:"t095",type:"truth",category:"personal",intensity:16,minPlayers:2,text:"What skill would you download instantly if you could?"},
  {id:"t096",type:"truth",category:"group",intensity:18,minPlayers:4,text:"Who here would do best in a zombie movie?"},
  {id:"t097",type:"truth",category:"icebreaker",intensity:20,minPlayers:2,text:"What food could you eat every week forever?"},
  {id:"t098",type:"truth",category:"funny",intensity:22,minPlayers:2,text:"What is the strangest nickname anyone has given you?"},
  {id:"t099",type:"truth",category:"personal",intensity:24,minPlayers:2,text:"What small luxury could you never give up?"},
  {id:"t100",type:"truth",category:"group",intensity:26,minPlayers:3,text:"Who here would be the calmest in an emergency?"},
  {id:"t101",type:"truth",category:"confession",intensity:28,minPlayers:2,text:"What chore do you avoid for as long as possible?"},
  {id:"t102",type:"truth",category:"personal",intensity:30,minPlayers:2,text:"What is a compliment you find hard to accept?"},
  {id:"t103",type:"truth",category:"group",intensity:32,minPlayers:4,text:"Who here is most likely to win a talent show?"},
  {id:"t104",type:"truth",category:"confession",intensity:34,minPlayers:2,text:"What trend did you follow that now embarrasses you?"},
  {id:"t105",type:"truth",category:"relationships",intensity:36,minPlayers:2,text:"What makes someone easy to talk to?"},
  {id:"t106",type:"truth",category:"personal",intensity:38,minPlayers:2,text:"What is a lesson you learned later than most people?"},
  {id:"t107",type:"truth",category:"group",intensity:39,minPlayers:3,text:"Who here would be the most convincing spy?"},
  {id:"t108",type:"truth",category:"confession",intensity:40,minPlayers:2,text:"What excuse have you used to cancel plans?"},
  {id:"t109",type:"truth",category:"relationships",intensity:42,minPlayers:2,text:"What makes you feel most appreciated?"},
  {id:"t110",type:"truth",category:"personal",intensity:44,minPlayers:2,text:"When did you last surprise yourself?"},
  {id:"t111",type:"truth",category:"group",intensity:46,minPlayers:4,text:"Who here would make the best detective?"},
  {id:"t112",type:"truth",category:"confession",intensity:48,minPlayers:2,text:"What have you pretended to like to fit in?"},
  {id:"t113",type:"truth",category:"relationships",intensity:50,minPlayers:2,text:"What is your love language when you really care?"},
  {id:"t114",type:"truth",category:"personal",intensity:52,minPlayers:2,text:"What difficult conversation are you glad you had?"},
  {id:"t115",type:"truth",category:"group",intensity:54,minPlayers:3,text:"Who here would you choose to host a podcast with?"},
  {id:"t116",type:"truth",category:"confession",intensity:56,minPlayers:2,text:"What is the pettiest argument you have tried to win?"},
  {id:"t117",type:"truth",category:"relationships",intensity:58,minPlayers:2,text:"What dating advice do you refuse to follow?"},
  {id:"t118",type:"truth",category:"personal",intensity:60,minPlayers:2,text:"What part of growing up has surprised you most?"},
  {id:"t119",type:"truth",category:"group",intensity:62,minPlayers:4,text:"Who here would be hardest to beat in an argument?"},
  {id:"t120",type:"truth",category:"confession",intensity:64,minPlayers:2,text:"When have you enjoyed proving someone wrong?"},
  {id:"t121",type:"truth",category:"relationships",intensity:66,minPlayers:2,text:"What behavior makes flirting obvious to you?"},
  {id:"t122",type:"truth",category:"personal",intensity:68,minPlayers:2,text:"What would you do if fear of failure disappeared?"},
  {id:"t123",type:"truth",category:"group",intensity:41,minPlayers:3,text:"Who here has the most contagious laugh?"},
  {id:"t124",type:"truth",category:"confession",intensity:45,minPlayers:2,text:"What have you borrowed and forgotten to return?"},
  {id:"t125",type:"truth",category:"relationships",intensity:53,minPlayers:2,text:"What makes a first date memorable for the right reasons?"},
  {id:"t126",type:"truth",category:"personal",intensity:57,minPlayers:2,text:"What are you secretly hoping changes this year?"},
  {id:"t127",type:"truth",category:"group",intensity:63,minPlayers:4,text:"Who here is most likely to marry spontaneously?"},
  {id:"t128",type:"truth",category:"confession",intensity:69,minPlayers:2,text:"Have you ever snooped and found something you regretted seeing?"},
  {id:"t129",type:"truth",category:"relationships",intensity:70,minPlayers:2,text:"What emotional quality do you find irresistible?"},
  {id:"t130",type:"truth",category:"confession",intensity:72,minPlayers:2,text:"Have you ever waited to reply just to seem less interested?"},
  {id:"t131",type:"truth",category:"group",intensity:74,minPlayers:3,text:"Who here would have the most surprising secret admirer?"},
  {id:"t132",type:"truth",category:"relationships",intensity:76,minPlayers:2,text:"What is the biggest risk you have taken for love?"},
  {id:"t133",type:"truth",category:"confession",intensity:78,minPlayers:2,text:"Have you ever flirted to get special treatment?"},
  {id:"t134",type:"truth",category:"personal",intensity:80,minPlayers:2,text:"What side of yourself do only close friends see?"},
  {id:"t135",type:"truth",category:"group",intensity:82,minPlayers:4,text:"Who here would be most dangerous with unlimited confidence?"},
  {id:"t136",type:"truth",category:"relationships",intensity:84,minPlayers:2,text:"What kind of attention makes you blush fastest?"},
  {id:"t137",type:"truth",category:"confession",intensity:86,minPlayers:2,text:"What romantic situation have you overanalyzed the most?"},
  {id:"t138",type:"truth",category:"personal",intensity:88,minPlayers:2,text:"What do you want that you are afraid to ask for?"},
  {id:"t139",type:"truth",category:"group",intensity:90,minPlayers:3,text:"Who here seems most likely to make the first move?"},
  {id:"t140",type:"truth",category:"relationships",intensity:92,minPlayers:2,text:"What does real romantic tension feel like to you?"},
  {id:"t141",type:"truth",category:"confession",intensity:94,minPlayers:2,text:"Have you ever wanted someone more after being told you could not have them?"},
  {id:"t142",type:"truth",category:"personal",intensity:96,minPlayers:2,text:"What private ambition would surprise people who know you?"},
  {id:"t143",type:"truth",category:"relationships",intensity:98,minPlayers:2,text:"What is the most intimate nonphysical moment you have shared?"},
  {id:"t144",type:"truth",category:"group",intensity:73,minPlayers:4,text:"Who here would thrive most on a dating show?"},
  {id:"t145",type:"truth",category:"confession",intensity:77,minPlayers:2,text:"Have you ever been attracted to someone because they were unavailable?"},
  {id:"t146",type:"truth",category:"relationships",intensity:83,minPlayers:2,text:"What romantic gesture would be too intense for you?"},
  {id:"t147",type:"truth",category:"personal",intensity:89,minPlayers:2,text:"What would your closest friend say is your romantic weakness?"},
  {id:"t148",type:"truth",category:"confession",intensity:95,minPlayers:2,text:"What feeling have you hidden to avoid changing a relationship?"},
  {id:"t149",type:"truth",category:"icebreaker",intensity:7,minPlayers:2,text:"What fictional character are you most like?"},
  {id:"t150",type:"truth",category:"funny",intensity:13,minPlayers:2,text:"What is your worst cooking disaster?"},
  {id:"t151",type:"truth",category:"group",intensity:19,minPlayers:3,text:"Who here would give the best acceptance speech?"},
  {id:"t152",type:"truth",category:"personal",intensity:25,minPlayers:2,text:"What subject could you give an unplanned lecture about?"},
  {id:"t153",type:"truth",category:"confession",intensity:31,minPlayers:2,text:"What have you googled because you were too embarrassed to ask?"},
  {id:"t154",type:"truth",category:"relationships",intensity:37,minPlayers:2,text:"What is your friendship red flag?"},
  {id:"t155",type:"truth",category:"group",intensity:43,minPlayers:4,text:"Who here is most likely to move abroad without warning?"},
  {id:"t156",type:"truth",category:"personal",intensity:49,minPlayers:2,text:"What is something you want to be remembered for?"},
  {id:"t157",type:"truth",category:"confession",intensity:55,minPlayers:2,text:"What social situation makes you feel most awkward?"},
  {id:"t158",type:"truth",category:"relationships",intensity:61,minPlayers:2,text:"What is your favorite kind of affectionate attention?"},
  {id:"t159",type:"truth",category:"group",intensity:67,minPlayers:3,text:"Who here would you trust to choose your blind date?"},
  {id:"t160",type:"truth",category:"confession",intensity:71,minPlayers:2,text:"Have you ever mistaken friendliness for flirting?"},
  {id:"t161",type:"truth",category:"relationships",intensity:75,minPlayers:2,text:"What makes someone unforgettable after one meeting?"},
  {id:"t162",type:"truth",category:"personal",intensity:79,minPlayers:2,text:"What vulnerable truth are you learning to say aloud?"},
  {id:"t163",type:"truth",category:"group",intensity:83,minPlayers:4,text:"Who here could most easily steal the spotlight on a date?"},
  {id:"t164",type:"truth",category:"confession",intensity:87,minPlayers:2,text:"What is the closest friendship you once mistook for romance?"},
  {id:"t165",type:"truth",category:"relationships",intensity:91,minPlayers:2,text:"What would make you break your usual dating rules?"},
  {id:"t166",type:"truth",category:"personal",intensity:93,minPlayers:2,text:"What romantic truth about yourself are you still figuring out?"},
  {id:"t167",type:"truth",category:"confession",intensity:97,minPlayers:2,text:"What is the hardest attraction you have had to ignore?"},
  {id:"t168",type:"truth",category:"relationships",intensity:99,minPlayers:2,text:"What kind of connection could tempt you to change your whole life?"},

  {id:"d089",type:"dare",category:"icebreaker",intensity:4,minPlayers:2,text:"Draw a heart in the air using your elbow."},
  {id:"d090",type:"dare",category:"funny",intensity:6,minPlayers:2,text:"Pretend your hand is a phone and answer an absurd call."},
  {id:"d091",type:"dare",category:"performance",intensity:8,minPlayers:2,text:"Sing your name like the opening of an opera."},
  {id:"d092",type:"dare",category:"group",intensity:10,minPlayers:3,text:"Lead everyone in a five-second round of applause."},
  {id:"d093",type:"dare",category:"funny",intensity:12,minPlayers:2,text:"Try to wink with both eyes one at a time."},
  {id:"d094",type:"dare",category:"performance",intensity:14,minPlayers:2,text:"Introduce yourself as a professional potato expert."},
  {id:"d095",type:"dare",category:"social",intensity:16,minPlayers:3,text:"Invent a cheerful greeting for the whole group."},
  {id:"d096",type:"dare",category:"group",intensity:18,minPlayers:4,text:"Choose a team name for everyone in the room."},
  {id:"d097",type:"dare",category:"funny",intensity:20,minPlayers:2,text:"Pretend to be a robot learning how to sit down."},
  {id:"d098",type:"dare",category:"performance",intensity:22,minPlayers:2,text:"Give a ten-second motivational speech to your drink."},
  {id:"d099",type:"dare",category:"social",intensity:24,minPlayers:3,text:"Compliment the person on your left using a rhyme."},
  {id:"d100",type:"dare",category:"group",intensity:26,minPlayers:4,text:"Assign everyone a character in an imaginary sitcom."},
  {id:"d101",type:"dare",category:"funny",intensity:28,minPlayers:2,text:"Attempt your most dramatic slow-motion fall without hitting the floor."},
  {id:"d102",type:"dare",category:"performance",intensity:30,minPlayers:2,text:"Mime your favorite hobby until someone guesses it."},
  {id:"d103",type:"dare",category:"social",intensity:32,minPlayers:3,text:"Give a one-sentence toast to the group."},
  {id:"d104",type:"dare",category:"group",intensity:34,minPlayers:4,text:"Start a three-word story and have everyone add three words."},
  {id:"d105",type:"dare",category:"funny",intensity:36,minPlayers:2,text:"Speak as if you are underwater until your next turn."},
  {id:"d106",type:"dare",category:"performance",intensity:38,minPlayers:2,text:"Demonstrate a made-up Olympic sport."},
  {id:"d107",type:"dare",category:"social",intensity:39,minPlayers:3,text:"Ask someone to teach you their signature pose."},
  {id:"d108",type:"dare",category:"group",intensity:40,minPlayers:4,text:"Let the group rename you until the next round."},
  {id:"d109",type:"dare",category:"performance",intensity:42,minPlayers:2,text:"Act out being late without using any words."},
  {id:"d110",type:"dare",category:"social",intensity:44,minPlayers:3,text:"Tell the person opposite you what job they would excel at."},
  {id:"d111",type:"dare",category:"group",intensity:46,minPlayers:4,text:"Create a group motto in under twenty seconds."},
  {id:"d112",type:"dare",category:"confession",intensity:48,minPlayers:2,text:"Reveal the last song you played and hum its chorus."},
  {id:"d113",type:"dare",category:"performance",intensity:50,minPlayers:2,text:"Perform a commercial for your best personality trait."},
  {id:"d114",type:"dare",category:"social",intensity:52,minPlayers:3,text:"Let another player choose an emotion for you to act out."},
  {id:"d115",type:"dare",category:"group",intensity:54,minPlayers:4,text:"Cast everyone in a fictional adventure movie."},
  {id:"d116",type:"dare",category:"confession",intensity:56,minPlayers:2,text:"Show the group your most recently used harmless emoji."},
  {id:"d117",type:"dare",category:"flirty",intensity:58,minPlayers:3,text:"Give the room your most confident entrance."},
  {id:"d118",type:"dare",category:"performance",intensity:60,minPlayers:2,text:"Reenact realizing your crush just walked into the room."},
  {id:"d119",type:"dare",category:"social",intensity:62,minPlayers:3,text:"Describe the person to your right as a fancy dessert."},
  {id:"d120",type:"dare",category:"group",intensity:64,minPlayers:4,text:"Let everyone contribute one word to your imaginary dating bio."},
  {id:"d121",type:"dare",category:"flirty",intensity:66,minPlayers:3,text:"Teach a consenting player your best playful pose."},
  {id:"d122",type:"dare",category:"confession",intensity:68,minPlayers:2,text:"Name a harmless celebrity crush and explain the appeal."},
  {id:"d123",type:"dare",category:"performance",intensity:41,minPlayers:2,text:"Read a nearby label like a dramatic prophecy."},
  {id:"d124",type:"dare",category:"social",intensity:45,minPlayers:3,text:"Give someone a compliment beginning with the first letter of their name."},
  {id:"d125",type:"dare",category:"group",intensity:53,minPlayers:4,text:"Invent a reality-show challenge for everyone in the room."},
  {id:"d126",type:"dare",category:"flirty",intensity:57,minPlayers:3,text:"Describe your ideal date using only gestures."},
  {id:"d127",type:"dare",category:"confession",intensity:63,minPlayers:2,text:"Say your cheesiest genuine romantic belief aloud."},
  {id:"d128",type:"dare",category:"flirty",intensity:69,minPlayers:3,text:"Deliver a playful wink to a consenting player or the camera."},
  {id:"d129",type:"dare",category:"performance",intensity:70,minPlayers:2,text:"Act out a terrible date in fifteen seconds."},
  {id:"d130",type:"dare",category:"flirty",intensity:72,minPlayers:3,text:"Give a consenting player a compliment in a movie-trailer voice."},
  {id:"d131",type:"dare",category:"group",intensity:74,minPlayers:4,text:"Let the group vote on your imaginary dating-show nickname."},
  {id:"d132",type:"dare",category:"confession",intensity:76,minPlayers:2,text:"Share a song that belongs on your romance soundtrack."},
  {id:"d133",type:"dare",category:"flirty",intensity:78,minPlayers:3,text:"Demonstrate your reaction to receiving a bold compliment."},
  {id:"d134",type:"dare",category:"performance",intensity:80,minPlayers:2,text:"Perform a soap-opera breakup with an empty chair."},
  {id:"d135",type:"dare",category:"group",intensity:82,minPlayers:4,text:"Let the group choose your fictional romantic superpower."},
  {id:"d136",type:"dare",category:"flirty",intensity:84,minPlayers:3,text:"Make up a sweet nickname for a consenting player."},
  {id:"d137",type:"dare",category:"confession",intensity:86,minPlayers:2,text:"Describe your usual flirting style in three honest words."},
  {id:"d138",type:"dare",category:"performance",intensity:88,minPlayers:2,text:"Act out trying not to stare at someone attractive."},
  {id:"d139",type:"dare",category:"flirty",intensity:90,minPlayers:3,text:"Give a consenting player a ten-second confidence pep talk."},
  {id:"d140",type:"dare",category:"group",intensity:92,minPlayers:4,text:"Let the group plan your outrageous fictional honeymoon."},
  {id:"d141",type:"dare",category:"confession",intensity:94,minPlayers:2,text:"Say one honest thing that makes you nervous about dating."},
  {id:"d142",type:"dare",category:"flirty",intensity:96,minPlayers:3,text:"Perform your boldest red-carpet pose beside a consenting player."},
  {id:"d143",type:"dare",category:"performance",intensity:98,minPlayers:2,text:"Pitch yourself as the lead in a steamy but tasteful romance film."},
  {id:"d144",type:"dare",category:"group",intensity:73,minPlayers:4,text:"Let the group choose your entrance song for a dream date."},
  {id:"d145",type:"dare",category:"flirty",intensity:77,minPlayers:3,text:"Tell a consenting player what makes their energy attractive."},
  {id:"d146",type:"dare",category:"confession",intensity:83,minPlayers:2,text:"Reveal a romantic movie scene you secretly love."},
  {id:"d147",type:"dare",category:"performance",intensity:89,minPlayers:2,text:"Act out getting caught sending a flirty text."},
  {id:"d148",type:"dare",category:"flirty",intensity:95,minPlayers:3,text:"Ask a consenting player one playful question they may freely decline."},
  {id:"d149",type:"dare",category:"icebreaker",intensity:7,minPlayers:2,text:"Make a crown from your hands and wear it for one round."},
  {id:"d150",type:"dare",category:"funny",intensity:13,minPlayers:2,text:"Explain how to make toast as if it is extremely complicated."},
  {id:"d151",type:"dare",category:"group",intensity:19,minPlayers:3,text:"Choose an imaginary mascot for the party."},
  {id:"d152",type:"dare",category:"performance",intensity:25,minPlayers:2,text:"Act like a tour guide showing off the room."},
  {id:"d153",type:"dare",category:"social",intensity:31,minPlayers:3,text:"Ask everyone to copy your funniest facial expression."},
  {id:"d154",type:"dare",category:"funny",intensity:37,minPlayers:2,text:"Try to make a heart shape with two unexpected objects."},
  {id:"d155",type:"dare",category:"group",intensity:43,minPlayers:4,text:"Give each player a role at an imaginary royal banquet."},
  {id:"d156",type:"dare",category:"performance",intensity:49,minPlayers:2,text:"Read the time as if announcing a historic event."},
  {id:"d157",type:"dare",category:"social",intensity:55,minPlayers:3,text:"Let the group choose your pose for ten seconds."},
  {id:"d158",type:"dare",category:"flirty",intensity:61,minPlayers:3,text:"Give your best playful hello to the person opposite you."},
  {id:"d159",type:"dare",category:"group",intensity:67,minPlayers:4,text:"Let the group create the title of your romantic autobiography."},
  {id:"d160",type:"dare",category:"confession",intensity:71,minPlayers:2,text:"Admit one harmless thing you do when you have a crush."},
  {id:"d161",type:"dare",category:"flirty",intensity:75,minPlayers:3,text:"Describe a consenting player’s vibe as a romantic vacation."},
  {id:"d162",type:"dare",category:"performance",intensity:79,minPlayers:2,text:"Act out your ideal movie-date montage."},
  {id:"d163",type:"dare",category:"group",intensity:83,minPlayers:4,text:"Let the group choose three traits for your perfect fictional match."},
  {id:"d164",type:"dare",category:"flirty",intensity:87,minPlayers:3,text:"Offer a consenting player your most theatrical invitation to dance."},
  {id:"d165",type:"dare",category:"confession",intensity:91,minPlayers:2,text:"Describe the last time someone made you blush."},
  {id:"d166",type:"dare",category:"performance",intensity:93,minPlayers:2,text:"Deliver a dramatic speech about forbidden attraction to a cushion."},
  {id:"d167",type:"dare",category:"flirty",intensity:97,minPlayers:3,text:"Create a daring but respectful pickup line for a consenting player."},
  {id:"d168",type:"dare",category:"group",intensity:99,minPlayers:4,text:"Let the group invent the plot of your scandalous fictional romance novel."}
];
