// Data-only prompt bank. Truth/dare intensity bands:
// 1 Easy, 2 Personal, 3 Spicy, 4 Adult, 5 Chaos, 6 Finale.
// Wildcards are independent of intensity.
window.PROMPTS = [
  {id:"t001",type:"truth",text:"What useless talent are you secretly proud of?",category:"icebreaker",intensity:1,minPlayers:2},
  {id:"t002",type:"truth",text:"Who was the last person you stalked on social media?",category:"icebreaker",intensity:1,minPlayers:2},
  {id:"t003",type:"truth",text:"What food combination do you love that others find strange?",category:"funny",intensity:1,minPlayers:2},
  {id:"t004",type:"truth",text:"What fictional world would you visit for one day?",category:"imagination",intensity:1,minPlayers:2},
  {id:"t005",type:"truth",text:"What your guilty-pleasure show/movie?",category:"icebreaker",intensity:1,minPlayers:2},
  {id:"t006",type:"truth",text:"What is your most-used emoji?",category:"icebreaker",intensity:1,minPlayers:2},
  {id:"t007",type:"truth",text:"What harmless lie do you tell surprisingly often?",category:"personal",intensity:1,minPlayers:2},
  {id:"t008",type:"truth",text:"Who here would survive longest on a deserted island?",category:"group",intensity:1,minPlayers:4},
  
  {id:"t009",type:"truth",text:"What habit are you currently trying to break?",category:"personal",intensity:2,minPlayers:2},
  {id:"t010",type:"truth",text:"Who here gave the worst first impression?",category:"group",intensity:2,minPlayers:3},
  {id:"t011",type:"truth",text:"Who here gives the best first impression?",category:"group",intensity:2,minPlayers:3},
  {id:"t012",type:"truth",text:"What celebrety would you want to have a hallpass on?",category:"personal",intensity:2,minPlayers:2},
  {id:"t013",type:"truth",text:"What is your biggest friendship green flag?",category:"relationships",intensity:2,minPlayers:2},
  {id:"t014",type:"truth",text:"Who was your first crush?",category:"confession",intensity:2,minPlayers:2},
  {id:"t015",type:"truth",text:"Who here would you trust to plan your birthday?",category:"group",intensity:2,minPlayers:3},
  {id:"t016",type:"truth",text:"What is something you wish you were better at?",category:"personal",intensity:2,minPlayers:2},

  {id:"t017",type:"truth",text:"Whats the most embarassing thing you've ever said while drunk?",category:"dating",intensity:3,minPlayers:2},
  {id:"t018",type:"truth",text:"Have you ever rehearsed a message before sending it?",category:"confession",intensity:3,minPlayers:2},
  {id:"t019",type:"truth",text:"Whats an unexpected turn-on?",category:"revealing",intensity:3,minPlayers:2},
  {id:"t020",type:"truth",text:"What is the boldest move you have made on a crush?",category:"dating",intensity:3,minPlayers:2},
  {id:"t021",type:"truth",text:"What part of your personality do people misunderstand?",category:"revealing",intensity:3,minPlayers:2},
  {id:"t022",type:"truth",text:"Who was the last person you flaked on and why?",category:"confession",intensity:2,minPlayers:2},
  {id:"t023",type:"truth",text:"What makes someone instantly more attractive to you?",category:"dating",intensity:3,minPlayers:2},
  {id:"t024",type:"truth",text:"What's the strongest drug you have ever tried?",category:"group",intensity:4,minPlayers:2},

  {id:"t025",type:"truth",text:"Have you ever caught feelings for someone you should not have?",category:"adult",intensity:3,minPlayers:2},
  {id:"t026",type:"truth",text:"What is your biggest nonphysical turn-on?",category:"adult",intensity:3,minPlayers:2},
  {id:"t027",type:"truth",text:"Whats your biggest physical turn-on?",category:"confession",intensity:3,minPlayers:2},
  {id:"t028",type:"truth",text:"Whats the worst date you have ever been on?",category:"group",intensity:3,minPlayers:1},
  {id:"t029",type:"truth",text:"What is the most romantic thing someone has done for you?",category:"dating",intensity:1,minPlayers:2},
  {id:"t030",type:"truth",text:"Have you ever flirted to get something for free?",category:"confession",intensity:4,minPlayers:2},
  {id:"t031",type:"truth",text:"What kind of chemistry is hardest for you to resist?",category:"adult",intensity:4,minPlayers:2},
  {id:"t032",type:"truth",text:"What boundary did you learn only after someone crossed it?",category:"revealing",intensity:4,minPlayers:2},

  {id:"t033",type:"truth",text:"What attraction have you tried hardest to deny?",category:"confession",intensity:5,minPlayers:2},
  {id:"t034",type:"truth",text:"Who here do you think has the wildest dating history?",category:"group",intensity:5,minPlayers:4},
  {id:"t035",type:"truth",text:"What is the riskiest romantic decision you have made?",category:"adult",intensity:5,minPlayers:2},
  {id:"t036",type:"truth",text:"Have you ever wanted someone more because they were unavailable?",category:"confession",intensity:5,minPlayers:2},
  {id:"t037",type:"truth",text:"What is the closest you have come to being caught in an intimate moment?",category:"adult",intensity:5,minPlayers:2},
  {id:"t038",type:"truth",text:"Who here would thrive most on a dating reality show?",category:"group",intensity:5,minPlayers:4},
  {id:"t039",type:"truth",text:"What feeling have you hidden to avoid changing a relationship?",category:"revealing",intensity:5,minPlayers:2},
  {id:"t040",type:"truth",text:"What is one bold romantic experience still on your bucket list?",category:"adult",intensity:5,minPlayers:2},

  {id:"t041",type:"truth",text:"What is the most chaotic thing you have done because of attraction?",category:"chaos",intensity:6,minPlayers:2},
  {id:"t042",type:"truth",text:"Which two people here would create the most dramatic fake couple?",category:"group",intensity:6,minPlayers:4},
  {id:"t043",type:"truth",text:"What private desire would surprise the people who know you best?",category:"adult",intensity:6,minPlayers:2},
  {id:"t044",type:"truth",text:"Have you ever risked a friendship by admitting your feelings?",category:"confession",intensity:6,minPlayers:2},
  {id:"t045",type:"truth",text:"Have you ever shot your shot and missed? Tell the story",category:"chaos",intensity:3,minPlayers:2},
  {id:"t046",type:"truth",text:"Who here could most easily convince you to make a bad decision?",category:"group",intensity:6,minPlayers:3},
  {id:"t047",type:"truth",text:"What is the boldest invitation you would genuinely say yes to tonight?",category:"adult",intensity:6,minPlayers:2},
  {id:"t048",type:"truth",text:"What kind of connection could tempt you to change your whole life?",category:"revealing",intensity:6,minPlayers:2},

  {id:"t049",type:"truth",text:"Who here would you not want to be stranded on an island with?",category:"group",intensity:2,minPlayers:2},
  {id:"t050",type:"truth",text:"Who here would you want to be stranded on a deserted island with?",category:"group",intensity:2,minPlayers:2},
  {id:"t051",type:"truth",text:"Who here would survive longest on a deserted island?",category:"group",intensity:1,minPlayers:2},
  {id:"t053",type:"truth",text:"Whats your top. 3 fastfoods places?",category:"food",intensity:1,minPlayers:2},
  {id:"t054",type:"truth",text:"What makes you think less of someone?",category:"group",intensity:2,minPlayers:2},
  {id:"t055",type:"truth",text:"Have you ever broken the law? If so which?",category:"group",intensity:3,minPlayers:2},
  {id:"t056",type:"truth",text:"Have you ever ghosted someone?",category:"group",intensity:1,minPlayers:2},
  {id:"t055",type:"truth",text:"Whats the worst thing you've done out of jealousy?",category:"group",intensity:3,minPlayers:2},
  {id:"t056",type:"truth",text:"?",category:"group",intensity:1,minPlayers:2},

  {id:"t057",type:"truth",text:"Biggest red flag you have ignored?",category:"group",intensity:2,minPlayers:2},
  {id:"t058",type:"truth",text:"Have you ever lied about something on a dating app?",category:"group",intensity:2,minPlayers:2},
  {id:"t058",type:"truth",text:"Whats something sexual you have allways wanted to try, but havent?",category:"group",intensity:3,minPlayers:2},
  {id:"t059",type:"truth",text:"If you had to kiss someone in this room, who would you choose?",category:"group",intensity:3,minPlayers:2},
  {id:"t060",type:"truth",text:"Whats the last complimet you recived?",category:"group",intensity:1,minPlayers:2},
  
  {id:"t061",type:"truth",text:"Whats the longest you've kept a crush secret?",category:"group",intensity:2,minPlayers:2},
  {id:"t062",type:"truth",text:"Who in the room would be the hardest person to date?",category:"group",intensity:3,minPlayers:3},
  {id:"t063",type:"truth",text:"Who's the first person you¨d call if you¨d gotten arrested?",category:"group",intensity:1,minPlayers:2},
  {id:"t064",type:"truth",text:"When were the last time you were jealous?",category:"group",intensity:2,minPlayers:2},
  {id:"t065",type:"truth",text:"Whats the coolest thing you own?",category:"group",intensity:1,minPlayers:2},

  {id:"t066",type:"truth",text:"Whats something that would immediately stop sex?",category:"group",intensity:1,minPlayers:2},
  {id:"t067",type:"truth",text:"Do you currently have a crush on someone?",category:"group",intensity:2,minPlayers:2},
  {id:"t068",type:"truth",text:"Whats the most risky photo you have ever sent?",category:"group",intensity:3,minPlayers:2},
  {id:"t069",type:"truth",text:"Whats the boldest thing you've ever asked someone to do in private?",category:"group",intensity:4,minPlayers:2},
  {id:"t070",type:"truth",text:"If you could get with one person from your past one more time, who would it be?",category:"group",intensity:4,minPlayers:2},

  {id:"t071",type:"truth",text:"Have you ever had anything up the backdoor during sex?",category:"group",intensity:4,minPlayers:2},
  {id:"t072",type:"truth",text:"Have you ever been attracted to two friends at the same time?",category:"group",intensity:3,minPlayers:2},
  {id:"t073",type:"truth",text:"placeholder1?",category:"group",intensity:4,minPlayers:2},
  {id:"t074",type:"truth",text:"placeholder2?",category:"group",intensity:4,minPlayers:2},
  {id:"t075",type:"truth",text:"placeholder3?",category:"group",intensity:4,minPlayers:2},


  {id:"d001",type:"dare",text:"Do your best victory dance for ten seconds.",category:"performance",intensity:1,minPlayers:2},
  {id:"d002",type:"dare",text:"Hum a song until someone guesses it.",category:"performance",intensity:1,minPlayers:2},
  {id:"d003",type:"dare",text:"Make your best animal sound.",category:"funny",intensity:1,minPlayers:2},
  {id:"d004",type:"dare",text:"Balance a harmless object on your head for one round.",category:"silly",intensity:1,minPlayers:2},
  {id:"d005",type:"dare",text:"Give the person to your left a sincere compliment.",category:"social",intensity:1,minPlayers:3},
  {id:"d006",type:"dare",text:"Speak like a movie narrator until your next turn.",category:"performance",intensity:1,minPlayers:2},
  {id:"d007",type:"dare",text:"Try to make the group laugh without speaking.",category:"funny",intensity:1,minPlayers:3},
  {id:"d008",type:"dare",text:"Invent a dance move and give it a ridiculous name.",category:"silly",intensity:1,minPlayers:2},

  {id:"d009",type:"dare",text:"Let another player choose an old social media post from one of your followers that you have to like and comment on.",category:"social",intensity:2,minPlayers:3},
  {id:"d010",type:"dare",text:"Show the last meme you saved, if you are comfortable.",category:"personal",intensity:2,minPlayers:2},
  {id:"d011",type:"dare",text:"Imitate someone in the room until they guess who.",category:"group",intensity:2,minPlayers:3},
  {id:"d012",type:"dare",text:"Perform the chorus of a song chosen by the group.",category:"performance",intensity:2,minPlayers:3},
  {id:"d013",type:"dare",text:"Tell two truths and a lie; let the group find the lie.",category:"social",intensity:2,minPlayers:3},
  {id:"d014",type:"dare",text:"Let another player choose a pose you must hold for ten seconds.",category:"silly",intensity:2,minPlayers:3},
  {id:"d015",type:"dare",text:"Read your recent emoji sequence like a serious poem.",category:"personal",intensity:2,minPlayers:2},
  {id:"d016",type:"dare",text:"Give everyone a one-word award.",category:"group",intensity:2,minPlayers:4},

  {id:"d017",type:"dare",text:"Deliver your best cheesy pickup line to the person opposite you.",category:"flirty",intensity:3,minPlayers:3},
  {id:"d018",type:"dare",text:"Hold eye contact with a willing player for fifteen seconds.",category:"flirty",intensity:3,minPlayers:3},
  {id:"d019",type:"dare",text:"Act out how you behave when you have a crush.",category:"performance",intensity:3,minPlayers:2},
  {id:"d020",type:"dare",text:"Describe your ideal first date in exactly ten words.",category:"dating",intensity:3,minPlayers:2},
  {id:"d021",type:"dare",text:"Give a genuine compliment to a player chosen by the group.",category:"social",intensity:3,minPlayers:3},
  {id:"d022",type:"dare",text:"Recreate your best dating-profile pose.",category:"flirty",intensity:3,minPlayers:2},
  {id:"d023",type:"dare",text:"Let the group write a three-word dating bio for you.",category:"group",intensity:3,minPlayers:4},
  {id:"d024",type:"dare",text:"Demonstrate your reaction to receiving a flirty message.",category:"performance",intensity:3,minPlayers:2},

  {id:"d025",type:"dare",text:"Whisper a playful compliment to a consenting player.",category:"flirty",intensity:4,minPlayers:3},
  {id:"d026",type:"dare",text:"Give your best intense movie-scene eye contact to a willing player.",category:"adult",intensity:4,minPlayers:3},
  {id:"d027",type:"dare",text:"Perform a ten-second slow dance alone or with a consenting player.",category:"performance",intensity:4,minPlayers:2},
  {id:"d028",type:"dare",text:"Describe the person opposite you as a romance-novel character.",category:"flirty",intensity:4,minPlayers:3},
  {id:"d029",type:"dare",text:"Let the group choose a romantic song for you to serenade.",category:"group",intensity:4,minPlayers:4},
  {id:"d030",type:"dare",text:"Give a willing player a twenty-second hand massage.",category:"adult",intensity:4,minPlayers:3},
  {id:"d031",type:"dare",text:"Reveal a harmless celebrity crush and defend your choice.",category:"confession",intensity:4,minPlayers:2},
  {id:"d032",type:"dare",text:"Read a menu item as though it were a passionate love letter.",category:"performance",intensity:4,minPlayers:2},

  {id:"d033",type:"dare",text:"Let the group direct your boldest dating-profile photo pose.",category:"chaos",intensity:5,minPlayers:4},
  {id:"d034",type:"dare",text:"Give a consenting player your most shameless pickup line.",category:"flirty",intensity:5,minPlayers:3},
  {id:"d035",type:"dare",text:"Act out getting caught sending a scandalous text.",category:"performance",intensity:5,minPlayers:2},
  {id:"d036",type:"dare",text:"Let the group choose someone for you to dramatically propose to.",category:"group",intensity:5,minPlayers:4},
  {id:"d037",type:"dare",text:"Describe your dream romantic night like a luxury advertisement.",category:"adult",intensity:5,minPlayers:2},
  {id:"d038",type:"dare",text:"Give a consenting player a playful nickname for the rest of the game.",category:"flirty",intensity:5,minPlayers:3},
  {id:"d039",type:"dare",text:"Show how you would make an entrance if everyone in the room wanted you.",category:"chaos",intensity:5,minPlayers:3},
  {id:"d040",type:"dare",text:"Let another player ask one bold question; answer or take your sip/skip.",category:"confession",intensity:5,minPlayers:3},

  {id:"d041",type:"dare",text:"Pitch yourself as the lead in an outrageous adult romance movie.",category:"chaos",intensity:6,minPlayers:2},
  {id:"d042",type:"dare",text:"Let the group invent the plot of your scandalous fictional autobiography.",category:"group",intensity:6,minPlayers:4},
  {id:"d043",type:"dare",text:"Ask a consenting player one provocative question they may freely decline.",category:"adult",intensity:6,minPlayers:3},
  {id:"d044",type:"dare",text:"Perform a dramatic forbidden-romance scene with a willing player or an object.",category:"performance",intensity:6,minPlayers:2},
  {id:"d045",type:"dare",text:"Let the group choose your fictional celebrity power-couple partner.",category:"chaos",intensity:6,minPlayers:4},
  {id:"d046",type:"dare",text:"Give a consenting player a compliment bold enough to make them blush.",category:"flirty",intensity:6,minPlayers:3},
  {id:"d047",type:"dare",text:"Describe your wildest dream date without naming a place or person.",category:"adult",intensity:6,minPlayers:2},
  {id:"d048",type:"dare",text:"Let the room design your chaotic alter ego, including name and dating style.",category:"group",intensity:6,minPlayers:4},

  {id:"w001",type:"wildcard",text:"You can skip one truth or dare, or pass it on to another player at any time",category:"power",minPlayers:2},
  {id:"w002",type:"wildcard",text:"Choose who has to do the next truth or dare.",category:"power",minPlayers:3},
  {id:"w003",type:"wildcard",text:"Finish your drink.",category:"rule",minPlayers:3},
  {id:"w004",type:"wildcard",text:"Select two players to become drinking partners.",category:"group",minPlayers:3},

  {id:"w005",type:"wildcard",text:"Decide whether the next selected player gets a Truth or Dare.",category:"power",minPlayers:3},
  {id:"w006",type:"wildcard",text:"Every player has to drink the amount of times the first letter in their name appears in their full legal name.",category:"rule",minPlayers:2},
  {id:"w007",type:"wildcard",text:"Have one sip pr week since the last time you got laid.",category:"power",minPlayers:3},
  {id:"w008",type:"wildcard",text:".",category:"group",minPlayers:4},

  {id:"w009",type:"wildcard",text:"One for you: Assign one sip/skip to any player.",category:"power",minPlayers:3},
  {id:"w010",type:"wildcard",text:"New rule: Two chosen players must speak in questions until your next turn.",category:"rule",minPlayers:4},
  {id:"w011",type:"wildcard",text:"Reverse: The next sip/skip assigned to you returns to its sender.",category:"power",minPlayers:3},
  {id:"w012",type:"wildcard",text:"Vote for the best storyteller. The winner assigns one sip/skip.",category:"group",minPlayers:4},

  {id:"w013",type:"wildcard",text:"Double shield: Protect yourself and one other player from one sip/skip each.",category:"power",minPlayers:3},
  {id:"w014",type:"wildcard",text:"New rule: Two players must call each other Your Majesty for one round.",category:"rule",minPlayers:4},
  {id:"w015",type:"wildcard",text:"Split decision: Give one sip/skip each to two different players.",category:"power",minPlayers:4},
  {id:"w016",type:"wildcard",text:"Hot seat: Ask a willing player one bold truth. They may answer or take one sip/skip.",category:"group",minPlayers:3},

  {id:"w017",type:"wildcard",text:"Dare dealer: Choose someone who must pick Dare next turn or use their sip/skip.",category:"power",minPlayers:3},
  {id:"w018",type:"wildcard",text:"New rule: Two chosen players must mirror each other for one round.",category:"rule",minPlayers:4},
  {id:"w019",type:"wildcard",text:"Chaos gift: Hand out two total sips/skips however you like.",category:"power",minPlayers:4},
  {id:"w020",type:"wildcard",text:"Council vote: Nominate the boldest player. They invent a respectful rule for one round.",category:"group",minPlayers:4},

  {id:"w021",type:"wildcard",text:"Royal decree: Create one respectful rule for everyone until your next turn.",category:"rule",minPlayers:4},
  {id:"w022",type:"wildcard",text:"Wild authority: Hand out three total sips/skips, at most one per player.",category:"power",minPlayers:4},
  {id:"w023",type:"wildcard",text:"Finale alliance: Pick two players to jointly choose the next person and prompt type.",category:"power",minPlayers:4},
  {id:"w024",type:"wildcard",text:"Chaos court: The group asks you one provocative question. Answer or assign two total sips/skips.",category:"group",minPlayers:4}
];
