// Data-only prompt bank. Intensity bands:
// 1 Easy, 2 Personal, 3 Spicy, 4 Adult, 5 Chaos, 6 Finale.
window.PROMPTS = [
  {id:"t001",type:"truth",text:"What useless talent are you secretly proud of?",category:"icebreaker",intensity:1,minPlayers:2},
  {id:"t002",type:"truth",text:"Which song can you sing without seeing the lyrics?",category:"icebreaker",intensity:1,minPlayers:2},
  {id:"t003",type:"truth",text:"What food combination do you love that others find strange?",category:"funny",intensity:1,minPlayers:2},
  {id:"t004",type:"truth",text:"What fictional world would you visit for one day?",category:"imagination",intensity:1,minPlayers:2},
  {id:"t005",type:"truth",text:"Who here would be the best game-show host?",category:"group",intensity:1,minPlayers:3},
  {id:"t006",type:"truth",text:"What is your most-used emoji?",category:"icebreaker",intensity:1,minPlayers:2},
  {id:"t007",type:"truth",text:"What tiny thing always improves your mood?",category:"personal",intensity:1,minPlayers:2},
  {id:"t008",type:"truth",text:"Who here would survive longest on a deserted island?",category:"group",intensity:1,minPlayers:4},

  {id:"t009",type:"truth",text:"What habit are you currently trying to break?",category:"personal",intensity:2,minPlayers:2},
  {id:"t010",type:"truth",text:"What compliment do you still remember?",category:"personal",intensity:2,minPlayers:2},
  {id:"t011",type:"truth",text:"Who here gives the best first impression?",category:"group",intensity:2,minPlayers:3},
  {id:"t012",type:"truth",text:"What opinion have you completely changed your mind about?",category:"personal",intensity:2,minPlayers:2},
  {id:"t013",type:"truth",text:"What is your biggest friendship green flag?",category:"relationships",intensity:2,minPlayers:2},
  {id:"t014",type:"truth",text:"What harmless lie do you tell surprisingly often?",category:"confession",intensity:2,minPlayers:2},
  {id:"t015",type:"truth",text:"Who here would you trust to plan your birthday?",category:"group",intensity:2,minPlayers:3},
  {id:"t016",type:"truth",text:"What is something you wish you were better at?",category:"personal",intensity:2,minPlayers:2},

  {id:"t017",type:"truth",text:"What is your most irrational dating deal-breaker?",category:"dating",intensity:3,minPlayers:2},
  {id:"t018",type:"truth",text:"Have you ever rehearsed a message before sending it?",category:"confession",intensity:3,minPlayers:2},
  {id:"t019",type:"truth",text:"Who here would make the best wingperson?",category:"group",intensity:3,minPlayers:3},
  {id:"t020",type:"truth",text:"What is the boldest move you have made on a crush?",category:"dating",intensity:3,minPlayers:2},
  {id:"t021",type:"truth",text:"What part of your personality do people misunderstand?",category:"revealing",intensity:3,minPlayers:2},
  {id:"t022",type:"truth",text:"Have you ever pretended not to see a message?",category:"confession",intensity:3,minPlayers:2},
  {id:"t023",type:"truth",text:"What makes someone instantly more attractive to you?",category:"dating",intensity:3,minPlayers:2},
  {id:"t024",type:"truth",text:"What was your honest first impression of the person opposite you?",category:"group",intensity:3,minPlayers:3},

  {id:"t025",type:"truth",text:"Have you ever caught feelings for someone you should not have?",category:"adult",intensity:4,minPlayers:2},
  {id:"t026",type:"truth",text:"What is your biggest nonphysical turn-on?",category:"adult",intensity:4,minPlayers:2},
  {id:"t027",type:"truth",text:"Have you ever kissed someone and immediately regretted it?",category:"confession",intensity:4,minPlayers:2},
  {id:"t028",type:"truth",text:"Who here would make you most nervous on a first date?",category:"group",intensity:4,minPlayers:3},
  {id:"t029",type:"truth",text:"What is the most romantic thing someone has done for you?",category:"dating",intensity:4,minPlayers:2},
  {id:"t030",type:"truth",text:"Have you ever flirted just for the attention?",category:"confession",intensity:4,minPlayers:2},
  {id:"t031",type:"truth",text:"What kind of chemistry is hardest for you to resist?",category:"adult",intensity:4,minPlayers:2},
  {id:"t032",type:"truth",text:"What boundary did you learn only after someone crossed it?",category:"revealing",intensity:4,minPlayers:2},

  {id:"t033",type:"truth",text:"What attraction have you tried hardest to deny?",category:"confession",intensity:5,minPlayers:2},
  {id:"t034",type:"truth",text:"Who here do you think has the wildest dating history?",category:"group",intensity:5,minPlayers:4},
  {id:"t035",type:"truth",text:"What is the riskiest romantic decision you have made?",category:"adult",intensity:5,minPlayers:2},
  {id:"t036",type:"truth",text:"Have you ever wanted someone more because they were unavailable?",category:"confession",intensity:5,minPlayers:2},
  {id:"t037",type:"truth",text:"What is the closest you have come to being caught in an intimate moment?",category:"adult",intensity:5,minPlayers:2},
  {id:"t038",type:"truth",text:"Who here would thrive most on a dating reality show?",category:"group",intensity:5,minPlayers:4},
  {id:"t039",type:"truth",text:"What feeling have you hidden to avoid changing a relationship?",category:"revealing",intensity:5,minPlayers:2},
  {id:"t040",type:"truth",text:"What is one bold romantic experience still on your bucket list?",category:"adult",intensity:5,minPlayers:2},

  {id:"t041",type:"truth",text:"What is the most chaotic thing you have done because of attraction?",category:"chaos",intensity:6,minPlayers:2},
  {id:"t042",type:"truth",text:"Which two people here would create the most dramatic fake couple?",category:"group",intensity:6,minPlayers:4},
  {id:"t043",type:"truth",text:"What private desire would surprise the people who know you best?",category:"adult",intensity:6,minPlayers:2},
  {id:"t044",type:"truth",text:"Have you ever risked a friendship by admitting your feelings?",category:"confession",intensity:6,minPlayers:2},
  {id:"t045",type:"truth",text:"What romantic rule would you break for the right person?",category:"chaos",intensity:6,minPlayers:2},
  {id:"t046",type:"truth",text:"Who here could most easily convince you to make a bad decision?",category:"group",intensity:6,minPlayers:3},
  {id:"t047",type:"truth",text:"What is the boldest invitation you would genuinely say yes to tonight?",category:"adult",intensity:6,minPlayers:2},
  {id:"t048",type:"truth",text:"What kind of connection could tempt you to change your whole life?",category:"revealing",intensity:6,minPlayers:2},

  {id:"d001",type:"dare",text:"Do your best victory dance for ten seconds.",category:"performance",intensity:1,minPlayers:2},
  {id:"d002",type:"dare",text:"Hum a song until someone guesses it.",category:"performance",intensity:1,minPlayers:2},
  {id:"d003",type:"dare",text:"Make your best animal sound.",category:"funny",intensity:1,minPlayers:2},
  {id:"d004",type:"dare",text:"Balance a harmless object on your head for one round.",category:"silly",intensity:1,minPlayers:2},
  {id:"d005",type:"dare",text:"Give the person to your left a sincere compliment.",category:"social",intensity:1,minPlayers:3},
  {id:"d006",type:"dare",text:"Speak like a movie narrator until your next turn.",category:"performance",intensity:1,minPlayers:2},
  {id:"d007",type:"dare",text:"Try to make the group laugh without speaking.",category:"funny",intensity:1,minPlayers:3},
  {id:"d008",type:"dare",text:"Invent a dance move and give it a ridiculous name.",category:"silly",intensity:1,minPlayers:2},

  {id:"d009",type:"dare",text:"Let the group give you a harmless nickname for two rounds.",category:"social",intensity:2,minPlayers:3},
  {id:"d010",type:"dare",text:"Show the last meme you saved, if you are comfortable.",category:"personal",intensity:2,minPlayers:2},
  {id:"d011",type:"dare",text:"Imitate someone in the room until they guess who.",category:"group",intensity:2,minPlayers:3},
  {id:"d012",type:"dare",text:"Perform the chorus of a song chosen by the group.",category:"performance",intensity:2,minPlayers:3},
  {id:"d013",type:"dare",text:"Tell two truths and a lie; let the group find the lie.",category:"social",intensity:2,minPlayers:3},
  {id:"d014",type:"dare",text:"Let another player choose a pose you must hold for ten seconds.",category:"silly",intensity:2,minPlayers:3},
  {id:"d015",type:"dare",text:"Read your recent emoji sequence like a serious poem.",category:"personal",intensity:2,minPlayers:2},
  {id:"d016",type:"dare",text:"Give everyone a one-word award.",category:"group",intensity:2,minPlayers:4},

  {id:"d017",type:"dare",text:"Deliver your best cheesy pickup line to the person opposite you.",category:"flirty",intensity:3,minPlayers:3},
  {id:"d018",type:"dare",text:"Hold eye contact with a willing player for fifteen seconds.",category:"flirty",intensity:3,minPlayers:3},
  {id:"d019",type:"dare",text:"Act out how you behave when you have a crush.",category:"performance",intensity:3,minPlayers:2},
  {id:"d020",type:"dare",text:"Describe your ideal first date in exactly ten words.",category:"dating",intensity:3,minPlayers:2},
  {id:"d021",type:"dare",text:"Give a genuine compliment to a player chosen by the group.",category:"social",intensity:3,minPlayers:3},
  {id:"d022",type:"dare",text:"Recreate your best dating-profile pose.",category:"flirty",intensity:3,minPlayers:2},
  {id:"d023",type:"dare",text:"Let the group write a three-word dating bio for you.",category:"group",intensity:3,minPlayers:4},
  {id:"d024",type:"dare",text:"Demonstrate your reaction to receiving a flirty message.",category:"performance",intensity:3,minPlayers:2},

  {id:"d025",type:"dare",text:"Whisper a playful compliment to a consenting player.",category:"flirty",intensity:4,minPlayers:3},
  {id:"d026",type:"dare",text:"Give your best intense movie-scene eye contact to a willing player.",category:"adult",intensity:4,minPlayers:3},
  {id:"d027",type:"dare",text:"Perform a ten-second slow dance alone or with a consenting player.",category:"performance",intensity:4,minPlayers:2},
  {id:"d028",type:"dare",text:"Describe the person opposite you as a romance-novel character.",category:"flirty",intensity:4,minPlayers:3},
  {id:"d029",type:"dare",text:"Let the group choose a romantic song for you to serenade.",category:"group",intensity:4,minPlayers:4},
  {id:"d030",type:"dare",text:"Give a willing player a twenty-second hand massage.",category:"adult",intensity:4,minPlayers:3},
  {id:"d031",type:"dare",text:"Reveal a harmless celebrity crush and defend your choice.",category:"confession",intensity:4,minPlayers:2},
  {id:"d032",type:"dare",text:"Read a menu item as though it were a passionate love letter.",category:"performance",intensity:4,minPlayers:2},

  {id:"d033",type:"dare",text:"Let the group direct your boldest dating-profile photo pose.",category:"chaos",intensity:5,minPlayers:4},
  {id:"d034",type:"dare",text:"Give a consenting player your most shameless pickup line.",category:"flirty",intensity:5,minPlayers:3},
  {id:"d035",type:"dare",text:"Act out getting caught sending a scandalous text.",category:"performance",intensity:5,minPlayers:2},
  {id:"d036",type:"dare",text:"Let the group choose someone for you to dramatically propose to.",category:"group",intensity:5,minPlayers:4},
  {id:"d037",type:"dare",text:"Describe your dream romantic night like a luxury advertisement.",category:"adult",intensity:5,minPlayers:2},
  {id:"d038",type:"dare",text:"Give a consenting player a playful nickname for the rest of the game.",category:"flirty",intensity:5,minPlayers:3},
  {id:"d039",type:"dare",text:"Show how you would make an entrance if everyone in the room wanted you.",category:"chaos",intensity:5,minPlayers:3},
  {id:"d040",type:"dare",text:"Let another player ask one bold question; answer or take your sip/skip.",category:"confession",intensity:5,minPlayers:3},

  {id:"d041",type:"dare",text:"Pitch yourself as the lead in an outrageous adult romance movie.",category:"chaos",intensity:6,minPlayers:2},
  {id:"d042",type:"dare",text:"Let the group invent the plot of your scandalous fictional autobiography.",category:"group",intensity:6,minPlayers:4},
  {id:"d043",type:"dare",text:"Ask a consenting player one provocative question they may freely decline.",category:"adult",intensity:6,minPlayers:3},
  {id:"d044",type:"dare",text:"Perform a dramatic forbidden-romance scene with a willing player or an object.",category:"performance",intensity:6,minPlayers:2},
  {id:"d045",type:"dare",text:"Let the group choose your fictional celebrity power-couple partner.",category:"chaos",intensity:6,minPlayers:4},
  {id:"d046",type:"dare",text:"Give a consenting player a compliment bold enough to make them blush.",category:"flirty",intensity:6,minPlayers:3},
  {id:"d047",type:"dare",text:"Describe your wildest dream date without naming a place or person.",category:"adult",intensity:6,minPlayers:2},
  {id:"d048",type:"dare",text:"Let the room design your chaotic alter ego, including name and dating style.",category:"group",intensity:6,minPlayers:4},

  {id:"w001",type:"wildcard",text:"Shield: Ignore one future sip/skip assignment.",category:"power",intensity:1,minPlayers:2},
  {id:"w002",type:"wildcard",text:"Director: Choose who spins the bottle next.",category:"power",intensity:1,minPlayers:3},
  {id:"w003",type:"wildcard",text:"New rule: Nobody may point with a finger until your next turn.",category:"rule",intensity:1,minPlayers:3},
  {id:"w004",type:"wildcard",text:"Team toast: Choose one player to make a toast with you.",category:"group",intensity:1,minPlayers:3},

  {id:"w005",type:"wildcard",text:"Choice: Decide whether the next selected player gets Truth or Dare.",category:"power",intensity:2,minPlayers:3},
  {id:"w006",type:"wildcard",text:"New rule: Choose a common word nobody may say for one round.",category:"rule",intensity:2,minPlayers:3},
  {id:"w007",type:"wildcard",text:"Alliance: Pick a teammate who may help with your next dare.",category:"power",intensity:2,minPlayers:3},
  {id:"w008",type:"wildcard",text:"Categories: Pick a topic and go around naming examples. First person stuck takes one sip/skip.",category:"group",intensity:2,minPlayers:4},

  {id:"w009",type:"wildcard",text:"One for you: Assign one sip/skip to any player.",category:"power",intensity:3,minPlayers:3},
  {id:"w010",type:"wildcard",text:"New rule: Two chosen players must speak in questions until your next turn.",category:"rule",intensity:3,minPlayers:4},
  {id:"w011",type:"wildcard",text:"Reverse: The next sip/skip assigned to you returns to its sender.",category:"power",intensity:3,minPlayers:3},
  {id:"w012",type:"wildcard",text:"Vote for the best storyteller. The winner assigns one sip/skip.",category:"group",intensity:3,minPlayers:4},

  {id:"w013",type:"wildcard",text:"Double shield: Protect yourself and one other player from one sip/skip each.",category:"power",intensity:4,minPlayers:3},
  {id:"w014",type:"wildcard",text:"New rule: Two players must call each other Your Majesty for one round.",category:"rule",intensity:4,minPlayers:4},
  {id:"w015",type:"wildcard",text:"Split decision: Give one sip/skip each to two different players.",category:"power",intensity:4,minPlayers:4},
  {id:"w016",type:"wildcard",text:"Hot seat: Ask a willing player one bold truth. They may answer or take one sip/skip.",category:"group",intensity:4,minPlayers:3},

  {id:"w017",type:"wildcard",text:"Dare dealer: Choose someone who must pick Dare next turn or use their sip/skip.",category:"power",intensity:5,minPlayers:3},
  {id:"w018",type:"wildcard",text:"New rule: Two chosen players must mirror each other for one round.",category:"rule",intensity:5,minPlayers:4},
  {id:"w019",type:"wildcard",text:"Chaos gift: Hand out two total sips/skips however you like.",category:"power",intensity:5,minPlayers:4},
  {id:"w020",type:"wildcard",text:"Council vote: Nominate the boldest player. They invent a respectful rule for one round.",category:"group",intensity:5,minPlayers:4},

  {id:"w021",type:"wildcard",text:"Royal decree: Create one respectful rule for everyone until your next turn.",category:"rule",intensity:6,minPlayers:4},
  {id:"w022",type:"wildcard",text:"Wild authority: Hand out three total sips/skips, at most one per player.",category:"power",intensity:6,minPlayers:4},
  {id:"w023",type:"wildcard",text:"Finale alliance: Pick two players to jointly choose the next person and prompt type.",category:"power",intensity:6,minPlayers:4},
  {id:"w024",type:"wildcard",text:"Chaos court: The group asks you one provocative question. Answer or assign two total sips/skips.",category:"group",intensity:6,minPlayers:4}
];
